name: material_toolkit_example
description: ""

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  material_toolkit:
    path: ../
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/sample.json
    - assets/images/orange.jpg
    - assets/svgs/fire.svg

  fonts:
    - family: Astronaut_PersonalUse
      fonts:
        - asset: assets/fonts/Astronaut_PersonalUse.otf
