name: material_toolkit
description: A toolkit for building custom design systems on top of Flutter's MaterialApp, offering enhanced flexibility and scalability for your app's visual identity.
version: 0.0.2
# author: Kevin Kobori <kevinyujikobori@gmail.com>
homepage: https://www.linkedin.com/in/kevin-kobori/
repository: https://github.com/Fluttely/material_toolkit

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  equatable: ^2.0.3
  gap: ^3.0.1
  universal_io: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0