name: material_toolkit
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  soundpool: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
