name: material_toolkit
description: A toolkit for building custom design systems on top of Flutter's MaterialApp, offering enhanced flexibility and scalability for your app's visual identity.
version: 0.2.0
# author: Kevin Kobori <https://www.linkedin.com/in/kevin-kobori/>
homepage:
repository: https://github.com/fluttely/material_toolkit

environment:
  sdk: ^3.8.1

dependencies:
  animations: ^2.0.11
  flutter:
    sdk: flutter
  material_design: ^0.2.5
  # material_design:
  #   path: packages/material_design

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
