name: material_toolkit
description: A toolkit for building custom design systems on top of Flutter's MaterialApp, offering enhanced flexibility and scalability for your app's visual identity.
version: 0.0.4
# author: Kevin Kobori <kevinyujikobori@gmail.com>
publisher: fluttely.com
homepage:
repository: https://github.com/fluttely/material_toolkit

environment:
  sdk: ^3.8.1

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.2.1
  universal_io: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
