// import 'package:flutter/foundation.dart';
// import 'package:flutter/material.dart';
// import 'package:get/get.dart';

// class XMaterialApp extends GetMaterialApp {
//   const XMaterialApp({
//     super.key,
//     super.navigatorKey,
//     super.scaffoldMessengerKey,
//     super.home,
//     super.routes = const <String, WidgetBuilder>{},
//     super.initialRoute,
//     super.onGenerateRoute,
//     super.onGenerateInitialRoutes,
//     super.onUnknownRoute,
//     super.useInheritedMediaQuery = false,
//     super.navigatorObservers = const <NavigatorObserver>[],
//     super.builder,
//     super.textDirection,
//     super.title = '',
//     super.onGenerateTitle,
//     super.color,
//     super.theme,
//     super.darkTheme,
//     super.themeMode = ThemeMode.system,
//     super.locale,
//     super.fallbackLocale,
//     super.localizationsDelegates,
//     super.localeListResolutionCallback,
//     super.localeResolutionCallback,
//     super.supportedLocales = const <Locale>[Locale('en', 'US')],
//     super.debugShowMaterialGrid = false,
//     super.showPerformanceOverlay = false,
//     super.checkerboardRasterCacheImages = false,
//     super.checkerboardOffscreenLayers = false,
//     super.showSemanticsDebugger = false,
//     super.debugShowCheckedModeBanner = true,
//     super.shortcuts,
//     super.scrollBehavior,
//     super.customTransition,
//     super.translationsKeys,
//     super.translations,
//     super.onInit,
//     super.onReady,
//     super.onDispose,
//     super.routingCallback,
//     super.defaultTransition,
//     super.getPages,
//     super.opaqueRoute,
//     super.enableLog = kDebugMode,
//     super.logWriterCallback,
//     super.popGesture,
//     super.transitionDuration,
//     super.defaultGlobalState,
//     super.smartManagement,
//     super.initialBinding,
//     super.unknownRoute,
//     super.highContrastTheme,
//     super.highContrastDarkTheme,
//     super.actions,
//   });

//   XMaterialApp.router({
//     Key? key,
//     RouteInformationProvider? routeInformationProvider,
//     RouteInformationParser<Object>? routeInformationParser,
//     RouterDelegate<Object>? routerDelegate,
//     BackButtonDispatcher? backButtonDispatcher,
//     TransitionBuilder? builder,
//     String? title,
//     GenerateAppTitle? onGenerateTitle,
//     ThemeData? theme,
//     ThemeData? darkTheme,
//     ThemeMode themeMode = ThemeMode.system,
//     Color? color,
//     Iterable<LocalizationsDelegate<dynamic>>? localizationsDelegates,
//     Iterable<Locale> supportedLocales = const <Locale>[Locale('en', 'US')],
//     bool debugShowMaterialGrid = false,
//     bool showPerformanceOverlay = false,
//     bool checkerboardRasterCacheImages = false,
//     bool checkerboardOffscreenLayers = false,
//     bool showSemanticsDebugger = false,
//     bool debugShowCheckedModeBanner = true,
//     Map<LogicalKeySet, Intent>? shortcuts,
//     ScrollBehavior? scrollBehavior,
//     ThemeData? highContrastTheme,
//     ThemeData? highContrastDarkTheme,
//     Map<Type, Action<Intent>>? actions,
//     bool useInheritedMediaQuery = false,
//     Locale? locale,
//     LocaleListResolutionCallback? localeListResolutionCallback,
//     LocaleResolutionCallback? localeResolutionCallback,
//     Locale? fallbackLocale,
//   }) : super.router(
//           key: key,
//           routeInformationProvider: routeInformationProvider,
//           routeInformationParser: routeInformationParser,
//           routerDelegate: routerDelegate,
//           backButtonDispatcher: backButtonDispatcher,
//           builder: builder,
//           title: title ?? '',
//           onGenerateTitle: onGenerateTitle,
//           color: color,
//           theme: theme,
//           darkTheme: darkTheme,
//           highContrastTheme: highContrastTheme,
//           highContrastDarkTheme: highContrastDarkTheme,
//           themeMode: themeMode,
//           localizationsDelegates: localizationsDelegates,
//           supportedLocales: supportedLocales,
//           debugShowMaterialGrid: debugShowMaterialGrid,
//           showPerformanceOverlay: showPerformanceOverlay,
//           checkerboardRasterCacheImages: checkerboardRasterCacheImages,
//           checkerboardOffscreenLayers: checkerboardOffscreenLayers,
//           showSemanticsDebugger: showSemanticsDebugger,
//           debugShowCheckedModeBanner: debugShowCheckedModeBanner,
//           shortcuts: shortcuts,
//           scrollBehavior: scrollBehavior,
//           actions: actions,
//           useInheritedMediaQuery: useInheritedMediaQuery,
//           locale: locale,
//           localeListResolutionCallback: localeListResolutionCallback,
//           localeResolutionCallback: localeResolutionCallback,
//           fallbackLocale: fallbackLocale,
//         );
// }
