// import 'package:flutter/widgets.dart';
// import 'package:remo_design_system/remo_design_system.dart';

// enum ApodTextLevel {
//   bodyMedium(XTextLevel.bodyMedium),
//   bodyLarge(XTextLevel.bodyLarge),
//   titleSmall(XTextLevel.titleSmall),
//   titleMedium(XTextLevel.titleMedium),
//   titleLarge(XTextLevel.titleLarge);

//   final XTextLevel xLevel;

//   const ApodTextLevel(this.xLevel);
// }

// class ApodText extends XText {
//   ApodText.(
//     String data, {
//     required ApodTextLevel level,
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super(
//           data,
//           xLevel: level.xLevel,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const Text(
//     String data, {
//     required TextStyle style,
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.custom(
//           data,
//           style: style,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const ApodText.labelSmall(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.labelSmall(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const ApodText.labelMedium(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.labelMedium(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const ApodText.labelLarge(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.labelLarge(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const ApodText.bodySmall(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.bodySmall(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const ApodText.bodyMedium(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.bodyMedium(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const ApodText.bodyLarge(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.bodyLarge(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const ApodText.titleSmall(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.titleSmall(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const ApodText.titleMedium(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.titleMedium(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const ApodText.titleLarge(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.titleLarge(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const ApodText.headlineSmall(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.headlineSmall(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const ApodText.headlineMedium(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.headlineMedium(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const ApodText.headlineLarge(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.headlineLarge(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const ApodText.displaySmall(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.displaySmall(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const ApodText.displayMedium(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.displayMedium(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const ApodText.displayLarge(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.displayLarge(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );
// }
